import { useState, useRef } from 'react';

export default function UploadZone({ onUpload, onSample, loading, error }) {
  const [dragging, setDragging] = useState(false);
  const [queued, setQueued] = useState([]);
  const inputRef = useRef(null);

  const handleFiles = (files) => {
    const pdfs = Array.from(files).filter(
      f => f.type === 'application/pdf' || f.name.endsWith('.pdf')
    );
    if (pdfs.length === 0) return;
    setQueued(prev => {
      const names = new Set(prev.map(f => f.name));
      return [...prev, ...pdfs.filter(f => !names.has(f.name))];
    });
  };

  const removeQueued = (name) =>
    setQueued(prev => prev.filter(f => f.name !== name));

  const handleDrop = (e) => {
    e.preventDefault();
    setDragging(false);
    handleFiles(e.dataTransfer.files);
  };

  const handleSubmit = () => {
    if (queued.length > 0) onUpload(queued);
  };

  return (
    <div className="upload-page">
      <div className="upload-card">
        <div className="title-icon">📈</div>
        <h2>Upload Diagnostics Reports</h2>
        <p className="subtitle">
          Drop one or more daily PDF reports generated by the Siemens System Diagnostics tool
          to instantly visualize memory, thread, and connection metrics.
        </p>

        <div
          className={`drop-zone ${dragging ? 'active' : ''}`}
          onDragOver={e => { e.preventDefault(); setDragging(true); }}
          onDragLeave={() => setDragging(false)}
          onDrop={handleDrop}
          onClick={() => inputRef.current?.click()}
        >
          <input
            ref={inputRef}
            type="file"
            accept=".pdf,application/pdf"
            multiple
            onChange={e => handleFiles(e.target.files)}
            onClick={e => e.stopPropagation()}
          />
          <div className="drop-icon">📂</div>
          <p><strong>Click to browse</strong> or drag & drop PDF files here</p>
          <p style={{ marginTop: '0.4rem', fontSize: '0.78rem' }}>
            Supports multiple files (daily_report_*.pdf)
          </p>
        </div>

        {queued.length > 0 && (
          <div className="file-list">
            {queued.map(f => (
              <span key={f.name} className="file-badge">
                📄 {f.name}
                <span className="remove" onClick={(e) => { e.stopPropagation(); removeQueued(f.name); }}>×</span>
              </span>
            ))}
          </div>
        )}

        {queued.length > 0 && (
          <button
            className="btn btn-primary"
            style={{ width: '100%', justifyContent: 'center', marginTop: '1rem', padding: '0.65rem' }}
            onClick={handleSubmit}
            disabled={loading}
          >
            {loading ? '⏳ Analysing…' : `🔍 Analyse ${queued.length} PDF${queued.length > 1 ? 's' : ''}`}
          </button>
        )}

        {error && (
          <div className="error-banner" style={{ marginTop: '1rem' }}>
            ⚠️ {error}
          </div>
        )}

        <div className="upload-divider">or</div>

        <button className="sample-btn" onClick={onSample} disabled={loading}>
          🎯 Load sample data (demo)
        </button>

        <div className="format-hint">
          <strong>Expected format:</strong> PDF files named <code>daily_report_YYYYMMdd.pdf</code>
          generated by the System Diagnostics scheduler. Each file contains up to 4 diagnostic
          snapshots per day with memory, thread, and network metrics.
        </div>
      </div>
    </div>
  );
}
